export const TMBD_ACCESS_TOKEN: string | undefined = process.env.TMDB_API_READ_ACCESS_TOKEN;
export const TMDB_API_KEY: string | undefined = process.env.TMDB_API_KEY;

export const TMDB_SEARCH_MOVIES = process.env.NEXT_PUBLIC_TMDB_SEARCH_MOVIES || '';
export const TMDB_POPULAR_MOVIES = process.env.NEXT_PUBLIC_TMDB_POPULAR_MOVIES || '';
export const TMDB_TOP_RATED_MOVIES = process.env.NEXT_PUBLIC_TMDB_TOP_RATED_MOVIES || '';
export const TMDB_POPULAR_TV_SHOWS = process.env.NEXT_PUBLIC_TMDB_POPULAR_TV_SHOWS || '';
export const TMDB_POPULAR_ARTISTS = process.env.NEXT_PUBLIC_TMDB_POPULAR_ARTISTS || '';

export const TMDB_ENDPOINTS = {
    SEARCH_MOVIES: TMDB_SEARCH_MOVIES,
    POPULAR_MOVIES: TMDB_POPULAR_MOVIES,
    TOP_RATED_MOVIES: TMDB_TOP_RATED_MOVIES,
    POPULAR_TV_SHOWS: TMDB_POPULAR_TV_SHOWS,
    POPULAR_ARTISTS: TMDB_POPULAR_ARTISTS,
};